#xngzj64v Ft-query(Retrieve and Create)
niyongaboaristide17/my-brand-api pull request #2
Opened 2022-01-28 15:45 UTC by niyongaboaristide17

### What does this PR
Query CRUD api
### Description of Task to be completed?
- ReadOne
- ReadAll
- Create
- Update
- Delete
### How should this be manually tested?
#### clone repo to locally
- git clone repo_link
#### install dependency
- npm install
#### Configure env
- create .env into the project folder
- copy .env.sample content to .env
- generate env variable content
#### Postman, curl or other api testing tool is used to test end points
##### create
- /api/v1/queries
##### read all
- /api/v1/queries
##### read one
- /api/v1/queries/{query_id}
##### update
- /api/v1/queries/{query_id}
##### delete
- /api/v1/queries/{query_id}

### What are the relevant pivotal tracker
- https://trello.com/b/xNgZJ64v/my-brand

### Screenshots
![Screenshot from 2022-01-28 16-24-12](https://user-images.githubusercontent.com/49604980/151576815-083e8514-a0d9-4453-ad98-1e5620ab1787.png)
![Screenshot from 2022-01-28 16-24-34](https://user-images.githubusercontent.com/49604980/151576820-349ad4f4-9e05-4bdf-b45e-fea69e8825b2.png)
![Screenshot from 2022-01-28 16-24-50](https://user-images.githubusercontent.com/49604980/151576822-3ec04ec0-85ec-4cdf-8241-6c6e482f3d24.png)
![Screenshot from 2022-01-28 16-25-03](https://user-images.githubusercontent.com/49604980/151576824-7c356d05-3940-4c5b-b78c-1bf8dbbf01a4.png)
![Screenshot from 2022-01-28 16-25-30](https://user-images.githubusercontent.com/49604980/151576829-f0f67e69-9888-4e71-af9e-4c92a13a5e1e.png)

2022-01-29 16:23 UTC, ncutixavier requested changes
Your PR title is not following naming convention

2022-01-29 16:23 UTC, ncutixavier commented on src/controllers/articleController.js
>  }
Add new line

2022-01-29 16:23 UTC, ncutixavier commented on src/controllers/queriesController.js
> +}
Add new line

2022-01-29 16:23 UTC, ncutixavier commented on src/models/query.js
> +export default Query
Add new line

2022-01-29 16:23 UTC, ncutixavier commented on src/services/queryServices.js
> +}
Add new line

2022-01-31 12:23 UTC, niyongaboaristide17 commented on src/models/query.js
> +export default Query
What line?

2022-01-31 12:23 UTC, niyongaboaristide17 commented on src/services/queryServices.js
> +}
What line?

2022-01-31 13:37 UTC, merged